### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by thePeras** [NIAEFEUP/sigarra-extension#11]

**Comment by thePeras** [comment]
@Naapperas suggested 'Roboto'

**Comment by LuisDuarte1** [comment]
A quick thought, I think that the font change should be enabled by default, is there any reason to not do this? cc: @toni-santos @ttoino 

Sigarra looks way better with the font change ^^

**Comment by toni-santos** [comment]
We could enable it by default, it would be make for a more striking difference when first installing the extension. I left it turned off by mere coincidence.

**Comment by LuisDuarte1** [comment]
> We could enable it by default, it would be make for a more striking difference when first installing the extension. I left it turned off by mere coincidence.

Yeah that's one of the reasons that I think we should have it enable it by default, and it just looks better :), good work on this, but if you don't mind creating a fast PR for enabling it by default I would appreciate it ^^
