### ISSUE TITLE
Schedule lunch break background looks weird

### ISSUE THREAD

**Issue by LuisDuarte1** [NIAEFEUP/sigarra-extension#120]
![image](https://github.com/NIAEFEUP/sigarra-extension/assets/24589619/51df6c3f-3aee-4a9b-a7c6-ec9913b444d2)

**Comment by LuisDuarte1** [comment]
Tabing out of the page and coming back in looks something like this, probably due to resize? cc. @toni-santos  @ttoino :
![image](https://github.com/NIAEFEUP/sigarra-extension/assets/24589619/6714b9ca-0741-418d-934e-cac742875459)

**Comment by ttoino** [comment]
> Tabing out of the page and coming back in looks something like this, probably due to resize? cc. @toni-santos  @ttoino :
> ![image](https://github.com/NIAEFEUP/sigarra-extension/assets/24589619/6714b9ca-0741-418d-934e-cac742875459)
> 

This is probably unrelated to tabbing out, I'm guessing it's an issue with overlapping classes, I'll look at it.
