### ISSUE TITLE
Hide elements from homepage

### ISSUE THREAD

**Issue by thePeras** [NIAEFEUP/sigarra-extension#4]
Some examples:

<div>
<img width="202" alt="Screenshot 2023-02-25 at 09 39 54" src="https://user-images.githubusercontent.com/53405284/221350259-a77fb9e8-0673-45c2-a9cc-0fe53d3a4335.png">
<img width="157" alt="Screenshot 2023-02-25 at 09 39 28" src="https://user-images.githubusercontent.com/53405284/221350262-4a5455c6-9683-4cda-9e02-871e4a6a6281.png">
<img width="1280" alt="Screenshot 2023-02-25 at 09 39 40" src="https://user-images.githubusercontent.com/53405284/221350264-45bb9acc-48e0-4582-8977-461f0851613a.png">
<div>

**Comment by lfsjesus** [comment]
Done! It is already merged.
![image](https://user-images.githubusercontent.com/29470214/222725719-1c00e6da-6f7f-455f-ba7b-a76297a8b6fc.png)
